### ISSUE TITLE
Task - Set up framework for home page for website

### ISSUE THREAD

**Issue by joshuawlee** [Allen-ISD-Computer-Science/REPO_CollegeAppsHelper_2024#6]
This will start off the development of the frontend. Need this page set up so other pages can be built off of it.

**Comment by RusticKnite** [comment]
Still a work in progress for today, hence why there isn't a commit for today. I need to check in with my group to make sure the styling is suitable for everyone's vison of the website. Also the template can be created once styling of the page is finalized. Most likely can commit tommorow.

**Comment by RusticKnite** [comment]
All components are set up all. The basic template is set up and other things such as animation and site information will be set up next week on the page.
